using System.Security.Claims;
using FluentAssertions;
using MCLS.Api.Authorization;
using MCLS.Infrastructure.Identity;
using Microsoft.AspNetCore.Authorization;
using Xunit;

namespace MCLS.UnitTests;

/// <summary>
/// The permission handler is the single gate every protected endpoint passes
/// through, so its behaviour is worth pinning down: it must fail closed.
/// </summary>
public class PermissionAuthorizationTests
{
    private static AuthorizationHandlerContext ContextFor(
        string requiredPermission, params string[] heldPermissions)
    {
        var claims = heldPermissions
            .Select(p => new Claim(JwtTokenService.PermissionClaimType, p))
            .ToList();

        var principal = new ClaimsPrincipal(new ClaimsIdentity(claims, "TestAuth"));
        var requirement = new PermissionRequirement(requiredPermission);

        return new AuthorizationHandlerContext([requirement], principal, resource: null);
    }

    [Fact]
    public async Task Succeeds_when_the_exact_permission_is_held()
    {
        var context = ContextFor("USER_MGMT.edit", "USER_MGMT.view", "USER_MGMT.edit");

        await new PermissionAuthorizationHandler().HandleAsync(context);

        context.HasSucceeded.Should().BeTrue();
    }

    [Fact]
    public async Task Fails_when_the_permission_is_absent()
    {
        var context = ContextFor("USER_MGMT.delete", "USER_MGMT.view", "USER_MGMT.edit");

        await new PermissionAuthorizationHandler().HandleAsync(context);

        context.HasSucceeded.Should().BeFalse();
    }

    [Fact]
    public async Task Fails_for_an_unauthenticated_caller()
    {
        var context = new AuthorizationHandlerContext(
            [new PermissionRequirement("DASHBOARD.view")],
            new ClaimsPrincipal(new ClaimsIdentity()),
            resource: null);

        await new PermissionAuthorizationHandler().HandleAsync(context);

        context.HasSucceeded.Should().BeFalse();
    }

    [Theory]
    [InlineData("user_mgmt.edit")]      // wrong case on the module
    [InlineData("USER_MGMT.EDIT")]      // wrong case on the right
    [InlineData("USER_MGMT.edi")]       // truncated
    [InlineData("USER_MGMT")]           // module only, no right
    public async Task Matching_is_exact_and_case_sensitive(string held)
    {
        // Permission keys are generated by the database, never typed by a user,
        // so a near-miss means a bug rather than a formatting difference. It
        // must not be treated as a match.
        var context = ContextFor("USER_MGMT.edit", held);

        await new PermissionAuthorizationHandler().HandleAsync(context);

        context.HasSucceeded.Should().BeFalse();
    }

    [Fact]
    public async Task Ignores_permission_values_carried_on_other_claim_types()
    {
        // A claim with the right value but the wrong type must not grant
        // anything: otherwise any claim source could mint permissions.
        var principal = new ClaimsPrincipal(new ClaimsIdentity(
            [new Claim(ClaimTypes.Role, "USER_MGMT.edit")], "TestAuth"));

        var context = new AuthorizationHandlerContext(
            [new PermissionRequirement("USER_MGMT.edit")], principal, resource: null);

        await new PermissionAuthorizationHandler().HandleAsync(context);

        context.HasSucceeded.Should().BeFalse();
    }
}

/// <summary>
/// The policy provider turns <c>perm:MODULE.right</c> into a requirement on
/// demand, so every module/right pair does not have to be registered up front.
/// </summary>
public class PermissionPolicyProviderTests
{
    private static PermissionPolicyProvider CreateProvider() =>
        new(Microsoft.Extensions.Options.Options.Create(new AuthorizationOptions()));

    [Fact]
    public async Task Builds_a_policy_for_a_prefixed_name()
    {
        var policy = await CreateProvider().GetPolicyAsync("perm:SECTORS.create");

        policy.Should().NotBeNull();
        policy!.Requirements.OfType<PermissionRequirement>()
            .Single().PermissionKey.Should().Be("SECTORS.create");
    }

    [Fact]
    public async Task Returns_null_for_an_unprefixed_name()
    {
        // Falls through to the default provider rather than inventing a policy.
        var policy = await CreateProvider().GetPolicyAsync("SomeOtherPolicy");

        policy.Should().BeNull();
    }

    [Fact]
    public async Task Returns_null_when_the_prefix_has_no_permission_after_it()
    {
        var policy = await CreateProvider().GetPolicyAsync("perm:");

        policy.Should().BeNull();
    }
}
