/*
    LGD / Census state and district codes.
    ------------------------------------------------------------------------
    Source: "All Districts of India" (784 districts, 36 states and UTs),
    supplied as the authoritative code list.

    Why this replaces the earlier seed: the portal receives a Udyam record whose
    address carries these official codes. Matching on district *name* is not
    safe — names are spelt several ways, several states reuse a name, and
    districts get renamed. The code is the stable key.

    States are matched to the existing master.State rows by name so their
    StateId (and every enterprise already pointing at it) is preserved; only the
    Code column is corrected. Districts are merged on (StateId, Code).

    Idempotent: re-running only updates.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/*
    State names differ between the portal's seed and the official list in three
    ways: case, "And" vs "and", and a leading "The" ("The Dadra And Nagar Haveli
    And Daman And Diu"). Matching on the raw string silently creates a duplicate
    state, so the comparison is normalised.
*/
CREATE OR ALTER FUNCTION dbo.fn_NormaliseStateName (@name nvarchar(200))
RETURNS nvarchar(200)
WITH SCHEMABINDING
AS
BEGIN
    DECLARE @n nvarchar(200) = LTRIM(RTRIM(LOWER(@name)));

    IF LEFT(@n, 4) = 'the ' SET @n = LTRIM(SUBSTRING(@n, 5, 200));

    SET @n = REPLACE(@n, ' and ', ' & ');
    SET @n = REPLACE(@n, '  ', ' ');

    RETURN @n;
END;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

-- Staging keeps the whole file in one set so the MERGEs below see it at once.
CREATE TABLE #Src
(
    StateCode    varchar(4)   NOT NULL,
    StateName    nvarchar(120) NOT NULL,
    DistrictCode varchar(6)   NOT NULL,
    DistrictName nvarchar(240) NOT NULL
);

INSERT INTO #Src (StateCode, StateName, DistrictCode, DistrictName) VALUES
    ('35', N'Andaman And Nicobar Islands', '603', N'Nicobars'),
    ('35', N'Andaman And Nicobar Islands', '632', N'North And Middle Andaman'),
    ('35', N'Andaman And Nicobar Islands', '602', N'South Andamans'),
    ('28', N'Andhra Pradesh', '745', N'Alluri Sitharama Raju'),
    ('28', N'Andhra Pradesh', '744', N'Anakapalli'),
    ('28', N'Andhra Pradesh', '502', N'Ananthapuramu'),
    ('28', N'Andhra Pradesh', '753', N'Annamayya'),
    ('28', N'Andhra Pradesh', '750', N'Bapatla'),
    ('28', N'Andhra Pradesh', '503', N'Chittoor'),
    ('28', N'Andhra Pradesh', '747', N'Dr. B.R. Ambedkar Konaseema'),
    ('28', N'Andhra Pradesh', '505', N'East Godavari'),
    ('28', N'Andhra Pradesh', '748', N'Eluru'),
    ('28', N'Andhra Pradesh', '506', N'Guntur'),
    ('28', N'Andhra Pradesh', '746', N'Kakinada'),
    ('28', N'Andhra Pradesh', '510', N'Krishna'),
    ('28', N'Andhra Pradesh', '511', N'Kurnool'),
    ('28', N'Andhra Pradesh', '790', N'Markapuram'),
    ('28', N'Andhra Pradesh', '755', N'Nandyal'),
    ('28', N'Andhra Pradesh', '749', N'Ntr'),
    ('28', N'Andhra Pradesh', '751', N'Palnadu'),
    ('28', N'Andhra Pradesh', '743', N'Parvathipuram Manyam'),
    ('28', N'Andhra Pradesh', '791', N'Polavaram'),
    ('28', N'Andhra Pradesh', '517', N'Prakasam'),
    ('28', N'Andhra Pradesh', '519', N'Srikakulam'),
    ('28', N'Andhra Pradesh', '515', N'Sri Potti Sriramulu Nellore'),
    ('28', N'Andhra Pradesh', '754', N'Sri Sathya Sai'),
    ('28', N'Andhra Pradesh', '752', N'Tirupati'),
    ('28', N'Andhra Pradesh', '520', N'Visakhapatnam'),
    ('28', N'Andhra Pradesh', '521', N'Vizianagaram'),
    ('28', N'Andhra Pradesh', '523', N'West Godavari'),
    ('28', N'Andhra Pradesh', '504', N'Y.S.R. Kadapa'),
    ('12', N'Arunachal Pradesh', '628', N'Anjaw'),
    ('12', N'Arunachal Pradesh', '787', N'Bichom'),
    ('12', N'Arunachal Pradesh', '229', N'Changlang'),
    ('12', N'Arunachal Pradesh', '230', N'Dibang Valley'),
    ('12', N'Arunachal Pradesh', '231', N'East Kameng'),
    ('12', N'Arunachal Pradesh', '232', N'East Siang'),
    ('12', N'Arunachal Pradesh', '718', N'Kamle'),
    ('12', N'Arunachal Pradesh', '786', N'Keyi Panyor'),
    ('12', N'Arunachal Pradesh', '677', N'Kra Daadi'),
    ('12', N'Arunachal Pradesh', '233', N'Kurung Kumey'),
    ('12', N'Arunachal Pradesh', '724', N'Leparada'),
    ('12', N'Arunachal Pradesh', '234', N'Lohit'),
    ('12', N'Arunachal Pradesh', '666', N'Longding'),
    ('12', N'Arunachal Pradesh', '235', N'Lower Dibang Valley'),
    ('12', N'Arunachal Pradesh', '719', N'Lower Siang'),
    ('12', N'Arunachal Pradesh', '236', N'Lower Subansiri'),
    ('12', N'Arunachal Pradesh', '678', N'Namsai'),
    ('12', N'Arunachal Pradesh', '723', N'Pakke Kessang'),
    ('12', N'Arunachal Pradesh', '237', N'Papum Pare'),
    ('12', N'Arunachal Pradesh', '725', N'Shi Yomi'),
    ('12', N'Arunachal Pradesh', '679', N'Siang'),
    ('12', N'Arunachal Pradesh', '238', N'Tawang'),
    ('12', N'Arunachal Pradesh', '239', N'Tirap'),
    ('12', N'Arunachal Pradesh', '240', N'Upper Siang'),
    ('12', N'Arunachal Pradesh', '241', N'Upper Subansiri'),
    ('12', N'Arunachal Pradesh', '242', N'West Kameng'),
    ('12', N'Arunachal Pradesh', '243', N'West Siang'),
    ('18', N'Assam', '739', N'Bajali'),
    ('18', N'Assam', '616', N'Baksa'),
    ('18', N'Assam', '280', N'Barpeta'),
    ('18', N'Assam', '705', N'Biswanath'),
    ('18', N'Assam', '281', N'Bongaigaon'),
    ('18', N'Assam', '282', N'Cachar'),
    ('18', N'Assam', '708', N'Charaideo'),
    ('18', N'Assam', '612', N'Chirang'),
    ('18', N'Assam', '283', N'Darrang'),
    ('18', N'Assam', '284', N'Dhemaji'),
    ('18', N'Assam', '285', N'Dhubri'),
    ('18', N'Assam', '286', N'Dibrugarh'),
    ('18', N'Assam', '299', N'Dima Hasao'),
    ('18', N'Assam', '287', N'Goalpara'),
    ('18', N'Assam', '288', N'Golaghat'),
    ('18', N'Assam', '289', N'Hailakandi'),
    ('18', N'Assam', '709', N'Hojai'),
    ('18', N'Assam', '290', N'Jorhat'),
    ('18', N'Assam', '291', N'Kamrup'),
    ('18', N'Assam', '618', N'Kamrup Metro'),
    ('18', N'Assam', '292', N'Karbi Anglong'),
    ('18', N'Assam', '294', N'Kokrajhar'),
    ('18', N'Assam', '295', N'Lakhimpur'),
    ('18', N'Assam', '706', N'Majuli'),
    ('18', N'Assam', '296', N'Marigaon'),
    ('18', N'Assam', '297', N'Nagaon'),
    ('18', N'Assam', '298', N'Nalbari'),
    ('18', N'Assam', '300', N'Sivasagar'),
    ('18', N'Assam', '301', N'Sonitpur'),
    ('18', N'Assam', '707', N'South Salmara Mancachar'),
    ('18', N'Assam', '293', N'Sribhumi'),
    ('18', N'Assam', '756', N'Tamulpur'),
    ('18', N'Assam', '302', N'Tinsukia'),
    ('18', N'Assam', '617', N'Udalguri'),
    ('18', N'Assam', '710', N'West Karbi Anglong'),
    ('10', N'Bihar', '188', N'Araria'),
    ('10', N'Bihar', '611', N'Arwal'),
    ('10', N'Bihar', '189', N'Aurangabad'),
    ('10', N'Bihar', '190', N'Banka'),
    ('10', N'Bihar', '191', N'Begusarai'),
    ('10', N'Bihar', '192', N'Bhagalpur'),
    ('10', N'Bihar', '193', N'Bhojpur'),
    ('10', N'Bihar', '194', N'Buxar'),
    ('10', N'Bihar', '195', N'Darbhanga'),
    ('10', N'Bihar', '196', N'Gaya'),
    ('10', N'Bihar', '197', N'Gopalganj'),
    ('10', N'Bihar', '198', N'Jamui'),
    ('10', N'Bihar', '199', N'Jehanabad'),
    ('10', N'Bihar', '200', N'Kaimur (Bhabua)'),
    ('10', N'Bihar', '201', N'Katihar'),
    ('10', N'Bihar', '202', N'Khagaria'),
    ('10', N'Bihar', '203', N'Kishanganj'),
    ('10', N'Bihar', '204', N'Lakhisarai'),
    ('10', N'Bihar', '205', N'Madhepura'),
    ('10', N'Bihar', '206', N'Madhubani'),
    ('10', N'Bihar', '207', N'Munger'),
    ('10', N'Bihar', '208', N'Muzaffarpur'),
    ('10', N'Bihar', '209', N'Nalanda'),
    ('10', N'Bihar', '210', N'Nawada'),
    ('10', N'Bihar', '211', N'Pashchim Champaran'),
    ('10', N'Bihar', '212', N'Patna'),
    ('10', N'Bihar', '213', N'Purbi Champaran'),
    ('10', N'Bihar', '214', N'Purnia'),
    ('10', N'Bihar', '215', N'Rohtas'),
    ('10', N'Bihar', '216', N'Saharsa'),
    ('10', N'Bihar', '217', N'Samastipur'),
    ('10', N'Bihar', '218', N'Saran'),
    ('10', N'Bihar', '219', N'Sheikhpura'),
    ('10', N'Bihar', '220', N'Sheohar'),
    ('10', N'Bihar', '221', N'Sitamarhi'),
    ('10', N'Bihar', '222', N'Siwan'),
    ('10', N'Bihar', '223', N'Supaul'),
    ('10', N'Bihar', '224', N'Vaishali'),
    ('4', N'Chandigarh', '44', N'Chandigarh'),
    ('22', N'Chhattisgarh', '646', N'Balod'),
    ('22', N'Chhattisgarh', '644', N'Balodabazar-Bhatapara'),
    ('22', N'Chhattisgarh', '649', N'Balrampur-Ramanujganj'),
    ('22', N'Chhattisgarh', '374', N'Bastar'),
    ('22', N'Chhattisgarh', '650', N'Bemetara'),
    ('22', N'Chhattisgarh', '636', N'Bijapur'),
    ('22', N'Chhattisgarh', '375', N'Bilaspur'),
    ('22', N'Chhattisgarh', '376', N'Dakshin Bastar Dantewada'),
    ('22', N'Chhattisgarh', '377', N'Dhamtari'),
    ('22', N'Chhattisgarh', '378', N'Durg'),
    ('22', N'Chhattisgarh', '645', N'Gariyaband'),
    ('22', N'Chhattisgarh', '734', N'Gaurela-Pendra-Marwahi'),
    ('22', N'Chhattisgarh', '379', N'Janjgir-Champa'),
    ('22', N'Chhattisgarh', '380', N'Jashpur'),
    ('22', N'Chhattisgarh', '382', N'Kabeerdham'),
    ('22', N'Chhattisgarh', '759', N'Khairagarh-Chhuikhadan-Gandai'),
    ('22', N'Chhattisgarh', '643', N'Kondagaon'),
    ('22', N'Chhattisgarh', '383', N'Korba'),
    ('22', N'Chhattisgarh', '384', N'Korea'),
    ('22', N'Chhattisgarh', '385', N'Mahasamund'),
    ('22', N'Chhattisgarh', '760', N'Manendragarh-Chirmiri-Bharatpur(M C B)'),
    ('22', N'Chhattisgarh', '761', N'Mohla-Manpur-Ambagarh Chouki'),
    ('22', N'Chhattisgarh', '647', N'Mungeli'),
    ('22', N'Chhattisgarh', '637', N'Narayanpur'),
    ('22', N'Chhattisgarh', '386', N'Raigarh'),
    ('22', N'Chhattisgarh', '387', N'Raipur'),
    ('22', N'Chhattisgarh', '388', N'Rajnandgaon'),
    ('22', N'Chhattisgarh', '762', N'Sakti'),
    ('22', N'Chhattisgarh', '763', N'Sarangarh-Bilaigarh'),
    ('22', N'Chhattisgarh', '642', N'Sukma'),
    ('22', N'Chhattisgarh', '648', N'Surajpur'),
    ('22', N'Chhattisgarh', '389', N'Surguja'),
    ('22', N'Chhattisgarh', '381', N'Uttar Bastar Kanker'),
    ('7', N'Delhi', '77', N'Central'),
    ('7', N'Delhi', '796', N'Central North'),
    ('7', N'Delhi', '78', N'East'),
    ('7', N'Delhi', '79', N'New Delhi'),
    ('7', N'Delhi', '80', N'North'),
    ('7', N'Delhi', '81', N'North East'),
    ('7', N'Delhi', '82', N'North West'),
    ('7', N'Delhi', '795', N'Old Delhi'),
    ('7', N'Delhi', '794', N'Outer North'),
    ('7', N'Delhi', '83', N'South'),
    ('7', N'Delhi', '670', N'South East'),
    ('7', N'Delhi', '84', N'South West'),
    ('7', N'Delhi', '85', N'West'),
    ('30', N'Goa', '793', N'Kushavati'),
    ('30', N'Goa', '551', N'North Goa'),
    ('30', N'Goa', '552', N'South Goa'),
    ('24', N'Gujarat', '438', N'Ahmedabad'),
    ('24', N'Gujarat', '439', N'Amreli'),
    ('24', N'Gujarat', '440', N'Anand'),
    ('24', N'Gujarat', '672', N'Arvalli'),
    ('24', N'Gujarat', '441', N'Banas Kantha'),
    ('24', N'Gujarat', '442', N'Bharuch'),
    ('24', N'Gujarat', '443', N'Bhavnagar'),
    ('24', N'Gujarat', '676', N'Botad'),
    ('24', N'Gujarat', '668', N'Chhotaudepur'),
    ('24', N'Gujarat', '445', N'Dahod'),
    ('24', N'Gujarat', '444', N'Dangs'),
    ('24', N'Gujarat', '674', N'Devbhumi Dwarka'),
    ('24', N'Gujarat', '446', N'Gandhinagar'),
    ('24', N'Gujarat', '675', N'Gir Somnath'),
    ('24', N'Gujarat', '447', N'Jamnagar'),
    ('24', N'Gujarat', '448', N'Junagadh'),
    ('24', N'Gujarat', '449', N'Kachchh'),
    ('24', N'Gujarat', '450', N'Kheda'),
    ('24', N'Gujarat', '451', N'Mahesana'),
    ('24', N'Gujarat', '669', N'Mahisagar'),
    ('24', N'Gujarat', '673', N'Morbi'),
    ('24', N'Gujarat', '452', N'Narmada'),
    ('24', N'Gujarat', '453', N'Navsari'),
    ('24', N'Gujarat', '454', N'Panch Mahals'),
    ('24', N'Gujarat', '455', N'Patan'),
    ('24', N'Gujarat', '456', N'Porbandar'),
    ('24', N'Gujarat', '457', N'Rajkot'),
    ('24', N'Gujarat', '458', N'Sabar Kantha'),
    ('24', N'Gujarat', '459', N'Surat'),
    ('24', N'Gujarat', '460', N'Surendranagar'),
    ('24', N'Gujarat', '641', N'Tapi'),
    ('24', N'Gujarat', '461', N'Vadodara'),
    ('24', N'Gujarat', '462', N'Valsad'),
    ('24', N'Gujarat', '789', N'Vav-Tharad'),
    ('6', N'Haryana', '58', N'Ambala'),
    ('6', N'Haryana', '59', N'Bhiwani'),
    ('6', N'Haryana', '701', N'Charkhi Dadri'),
    ('6', N'Haryana', '60', N'Faridabad'),
    ('6', N'Haryana', '61', N'Fatehabad'),
    ('6', N'Haryana', '62', N'Gurugram'),
    ('6', N'Haryana', '792', N'Hansi'),
    ('6', N'Haryana', '63', N'Hisar'),
    ('6', N'Haryana', '64', N'Jhajjar'),
    ('6', N'Haryana', '65', N'Jind'),
    ('6', N'Haryana', '66', N'Kaithal'),
    ('6', N'Haryana', '67', N'Karnal'),
    ('6', N'Haryana', '68', N'Kurukshetra'),
    ('6', N'Haryana', '69', N'Mahendragarh'),
    ('6', N'Haryana', '604', N'Nuh'),
    ('6', N'Haryana', '619', N'Palwal'),
    ('6', N'Haryana', '70', N'Panchkula'),
    ('6', N'Haryana', '71', N'Panipat'),
    ('6', N'Haryana', '72', N'Rewari'),
    ('6', N'Haryana', '73', N'Rohtak'),
    ('6', N'Haryana', '74', N'Sirsa'),
    ('6', N'Haryana', '75', N'Sonipat'),
    ('6', N'Haryana', '76', N'Yamunanagar'),
    ('2', N'Himachal Pradesh', '15', N'Bilaspur'),
    ('2', N'Himachal Pradesh', '16', N'Chamba'),
    ('2', N'Himachal Pradesh', '17', N'Hamirpur'),
    ('2', N'Himachal Pradesh', '18', N'Kangra'),
    ('2', N'Himachal Pradesh', '19', N'Kinnaur'),
    ('2', N'Himachal Pradesh', '20', N'Kullu'),
    ('2', N'Himachal Pradesh', '21', N'Lahaul And Spiti'),
    ('2', N'Himachal Pradesh', '22', N'Mandi'),
    ('2', N'Himachal Pradesh', '23', N'Shimla'),
    ('2', N'Himachal Pradesh', '24', N'Sirmaur'),
    ('2', N'Himachal Pradesh', '25', N'Solan'),
    ('2', N'Himachal Pradesh', '26', N'Una'),
    ('1', N'Jammu And Kashmir', '1', N'Anantnag'),
    ('1', N'Jammu And Kashmir', '623', N'Bandipora'),
    ('1', N'Jammu And Kashmir', '3', N'Baramulla'),
    ('1', N'Jammu And Kashmir', '2', N'Budgam'),
    ('1', N'Jammu And Kashmir', '4', N'Doda'),
    ('1', N'Jammu And Kashmir', '626', N'Ganderbal'),
    ('1', N'Jammu And Kashmir', '5', N'Jammu'),
    ('1', N'Jammu And Kashmir', '7', N'Kathua'),
    ('1', N'Jammu And Kashmir', '620', N'Kishtwar'),
    ('1', N'Jammu And Kashmir', '622', N'Kulgam'),
    ('1', N'Jammu And Kashmir', '8', N'Kupwara'),
    ('1', N'Jammu And Kashmir', '10', N'Poonch'),
    ('1', N'Jammu And Kashmir', '11', N'Pulwama'),
    ('1', N'Jammu And Kashmir', '12', N'Rajouri'),
    ('1', N'Jammu And Kashmir', '621', N'Ramban'),
    ('1', N'Jammu And Kashmir', '627', N'Reasi'),
    ('1', N'Jammu And Kashmir', '624', N'Samba'),
    ('1', N'Jammu And Kashmir', '625', N'Shopian'),
    ('1', N'Jammu And Kashmir', '13', N'Srinagar'),
    ('1', N'Jammu And Kashmir', '14', N'Udhampur'),
    ('20', N'Jharkhand', '322', N'Bokaro'),
    ('20', N'Jharkhand', '323', N'Chatra'),
    ('20', N'Jharkhand', '324', N'Deoghar'),
    ('20', N'Jharkhand', '325', N'Dhanbad'),
    ('20', N'Jharkhand', '326', N'Dumka'),
    ('20', N'Jharkhand', '327', N'East Singhbum'),
    ('20', N'Jharkhand', '328', N'Garhwa'),
    ('20', N'Jharkhand', '329', N'Giridih'),
    ('20', N'Jharkhand', '330', N'Godda'),
    ('20', N'Jharkhand', '331', N'Gumla'),
    ('20', N'Jharkhand', '332', N'Hazaribagh'),
    ('20', N'Jharkhand', '333', N'Jamtara'),
    ('20', N'Jharkhand', '606', N'Khunti'),
    ('20', N'Jharkhand', '334', N'Koderma'),
    ('20', N'Jharkhand', '335', N'Latehar'),
    ('20', N'Jharkhand', '336', N'Lohardaga'),
    ('20', N'Jharkhand', '337', N'Pakur'),
    ('20', N'Jharkhand', '338', N'Palamu'),
    ('20', N'Jharkhand', '607', N'Ramgarh'),
    ('20', N'Jharkhand', '339', N'Ranchi'),
    ('20', N'Jharkhand', '340', N'Sahebganj'),
    ('20', N'Jharkhand', '341', N'Saraikela Kharsawan'),
    ('20', N'Jharkhand', '342', N'Simdega'),
    ('20', N'Jharkhand', '343', N'West Singhbhum'),
    ('29', N'Karnataka', '524', N'Bagalkote'),
    ('29', N'Karnataka', '528', N'Ballari'),
    ('29', N'Karnataka', '527', N'Belagavi'),
    ('29', N'Karnataka', '526', N'Bengaluru Rural'),
    ('29', N'Karnataka', '631', N'Bengaluru South'),
    ('29', N'Karnataka', '525', N'Bengaluru Urban'),
    ('29', N'Karnataka', '529', N'Bidar'),
    ('29', N'Karnataka', '531', N'Chamarajanagar'),
    ('29', N'Karnataka', '630', N'Chikkaballapura'),
    ('29', N'Karnataka', '532', N'Chikkamagaluru'),
    ('29', N'Karnataka', '533', N'Chitradurga'),
    ('29', N'Karnataka', '534', N'Dakshina Kannada'),
    ('29', N'Karnataka', '535', N'Davanagere'),
    ('29', N'Karnataka', '536', N'Dharwad'),
    ('29', N'Karnataka', '537', N'Gadag'),
    ('29', N'Karnataka', '539', N'Hassan'),
    ('29', N'Karnataka', '540', N'Haveri'),
    ('29', N'Karnataka', '538', N'Kalaburagi'),
    ('29', N'Karnataka', '541', N'Kodagu'),
    ('29', N'Karnataka', '542', N'Kolar'),
    ('29', N'Karnataka', '543', N'Koppal'),
    ('29', N'Karnataka', '544', N'Mandya'),
    ('29', N'Karnataka', '545', N'Mysuru'),
    ('29', N'Karnataka', '546', N'Raichur'),
    ('29', N'Karnataka', '547', N'Shivamogga'),
    ('29', N'Karnataka', '548', N'Tumakuru'),
    ('29', N'Karnataka', '549', N'Udupi'),
    ('29', N'Karnataka', '550', N'Uttara Kannada'),
    ('29', N'Karnataka', '738', N'Vijayanagara'),
    ('29', N'Karnataka', '530', N'Vijayapura'),
    ('29', N'Karnataka', '635', N'Yadgir'),
    ('32', N'Kerala', '554', N'Alappuzha'),
    ('32', N'Kerala', '555', N'Ernakulam'),
    ('32', N'Kerala', '556', N'Idukki'),
    ('32', N'Kerala', '557', N'Kannur'),
    ('32', N'Kerala', '558', N'Kasaragod'),
    ('32', N'Kerala', '559', N'Kollam'),
    ('32', N'Kerala', '560', N'Kottayam'),
    ('32', N'Kerala', '561', N'Kozhikode'),
    ('32', N'Kerala', '562', N'Malappuram'),
    ('32', N'Kerala', '563', N'Palakkad'),
    ('32', N'Kerala', '564', N'Pathanamthitta'),
    ('32', N'Kerala', '565', N'Thiruvananthapuram'),
    ('32', N'Kerala', '566', N'Thrissur'),
    ('32', N'Kerala', '567', N'Wayanad'),
    ('37', N'Ladakh', '6', N'Kargil'),
    ('37', N'Ladakh', '9', N'Leh Ladakh'),
    ('31', N'Lakshadweep', '553', N'Lakshadweep District'),
    ('23', N'Madhya Pradesh', '667', N'Agar-Malwa'),
    ('23', N'Madhya Pradesh', '639', N'Alirajpur'),
    ('23', N'Madhya Pradesh', '390', N'Anuppur'),
    ('23', N'Madhya Pradesh', '391', N'Ashoknagar'),
    ('23', N'Madhya Pradesh', '392', N'Balaghat'),
    ('23', N'Madhya Pradesh', '393', N'Barwani'),
    ('23', N'Madhya Pradesh', '394', N'Betul'),
    ('23', N'Madhya Pradesh', '395', N'Bhind'),
    ('23', N'Madhya Pradesh', '396', N'Bhopal'),
    ('23', N'Madhya Pradesh', '397', N'Burhanpur'),
    ('23', N'Madhya Pradesh', '398', N'Chhatarpur'),
    ('23', N'Madhya Pradesh', '399', N'Chhindwara'),
    ('23', N'Madhya Pradesh', '400', N'Damoh'),
    ('23', N'Madhya Pradesh', '401', N'Datia'),
    ('23', N'Madhya Pradesh', '402', N'Dewas'),
    ('23', N'Madhya Pradesh', '403', N'Dhar'),
    ('23', N'Madhya Pradesh', '404', N'Dindori'),
    ('23', N'Madhya Pradesh', '406', N'Guna'),
    ('23', N'Madhya Pradesh', '407', N'Gwalior'),
    ('23', N'Madhya Pradesh', '408', N'Harda'),
    ('23', N'Madhya Pradesh', '410', N'Indore'),
    ('23', N'Madhya Pradesh', '411', N'Jabalpur'),
    ('23', N'Madhya Pradesh', '412', N'Jhabua'),
    ('23', N'Madhya Pradesh', '413', N'Katni'),
    ('23', N'Madhya Pradesh', '405', N'Khandwa (East Nimar)'),
    ('23', N'Madhya Pradesh', '414', N'Khargone (West Nimar)'),
    ('23', N'Madhya Pradesh', '784', N'Maihar'),
    ('23', N'Madhya Pradesh', '415', N'Mandla'),
    ('23', N'Madhya Pradesh', '416', N'Mandsaur'),
    ('23', N'Madhya Pradesh', '766', N'MAUGANJ'),
    ('23', N'Madhya Pradesh', '417', N'Morena'),
    ('23', N'Madhya Pradesh', '409', N'Narmadapuram'),
    ('23', N'Madhya Pradesh', '418', N'Narsimhapur'),
    ('23', N'Madhya Pradesh', '419', N'Neemuch'),
    ('23', N'Madhya Pradesh', '722', N'Niwari'),
    ('23', N'Madhya Pradesh', '785', N'Pandhurna'),
    ('23', N'Madhya Pradesh', '420', N'Panna'),
    ('23', N'Madhya Pradesh', '421', N'Raisen'),
    ('23', N'Madhya Pradesh', '422', N'Rajgarh'),
    ('23', N'Madhya Pradesh', '423', N'Ratlam'),
    ('23', N'Madhya Pradesh', '424', N'Rewa'),
    ('23', N'Madhya Pradesh', '425', N'Sagar'),
    ('23', N'Madhya Pradesh', '426', N'Satna'),
    ('23', N'Madhya Pradesh', '427', N'Sehore'),
    ('23', N'Madhya Pradesh', '428', N'Seoni'),
    ('23', N'Madhya Pradesh', '429', N'Shahdol'),
    ('23', N'Madhya Pradesh', '430', N'Shajapur'),
    ('23', N'Madhya Pradesh', '431', N'Sheopur'),
    ('23', N'Madhya Pradesh', '432', N'Shivpuri'),
    ('23', N'Madhya Pradesh', '433', N'Sidhi'),
    ('23', N'Madhya Pradesh', '638', N'Singrauli'),
    ('23', N'Madhya Pradesh', '434', N'Tikamgarh'),
    ('23', N'Madhya Pradesh', '435', N'Ujjain'),
    ('23', N'Madhya Pradesh', '436', N'Umaria'),
    ('23', N'Madhya Pradesh', '437', N'Vidisha'),
    ('27', N'Maharashtra', '466', N'Ahilyanagar'),
    ('27', N'Maharashtra', '467', N'Akola'),
    ('27', N'Maharashtra', '468', N'Amravati'),
    ('27', N'Maharashtra', '470', N'Beed'),
    ('27', N'Maharashtra', '471', N'Bhandara'),
    ('27', N'Maharashtra', '472', N'Buldhana'),
    ('27', N'Maharashtra', '473', N'Chandrapur'),
    ('27', N'Maharashtra', '469', N'Chhatrapati Sambhajinagar'),
    ('27', N'Maharashtra', '488', N'Dharashiv'),
    ('27', N'Maharashtra', '474', N'Dhule'),
    ('27', N'Maharashtra', '475', N'Gadchiroli'),
    ('27', N'Maharashtra', '476', N'Gondia'),
    ('27', N'Maharashtra', '477', N'Hingoli'),
    ('27', N'Maharashtra', '478', N'Jalgaon'),
    ('27', N'Maharashtra', '479', N'Jalna'),
    ('27', N'Maharashtra', '480', N'Kolhapur'),
    ('27', N'Maharashtra', '481', N'Latur'),
    ('27', N'Maharashtra', '482', N'Mumbai'),
    ('27', N'Maharashtra', '483', N'Mumbai Suburban'),
    ('27', N'Maharashtra', '484', N'Nagpur'),
    ('27', N'Maharashtra', '485', N'Nanded'),
    ('27', N'Maharashtra', '486', N'Nandurbar'),
    ('27', N'Maharashtra', '487', N'Nashik'),
    ('27', N'Maharashtra', '665', N'Palghar'),
    ('27', N'Maharashtra', '489', N'Parbhani'),
    ('27', N'Maharashtra', '490', N'Pune'),
    ('27', N'Maharashtra', '491', N'Raigad'),
    ('27', N'Maharashtra', '492', N'Ratnagiri'),
    ('27', N'Maharashtra', '493', N'Sangli'),
    ('27', N'Maharashtra', '494', N'Satara'),
    ('27', N'Maharashtra', '495', N'Sindhudurg'),
    ('27', N'Maharashtra', '496', N'Solapur'),
    ('27', N'Maharashtra', '497', N'Thane'),
    ('27', N'Maharashtra', '498', N'Wardha'),
    ('27', N'Maharashtra', '499', N'Washim'),
    ('27', N'Maharashtra', '500', N'Yavatmal'),
    ('14', N'Manipur', '252', N'Bishnupur'),
    ('14', N'Manipur', '253', N'Chandel'),
    ('14', N'Manipur', '254', N'Churachandpur'),
    ('14', N'Manipur', '255', N'Imphal East'),
    ('14', N'Manipur', '256', N'Imphal West'),
    ('14', N'Manipur', '713', N'Jiribam'),
    ('14', N'Manipur', '711', N'Kakching'),
    ('14', N'Manipur', '717', N'Kamjong'),
    ('14', N'Manipur', '712', N'Kangpokpi'),
    ('14', N'Manipur', '714', N'Noney'),
    ('14', N'Manipur', '715', N'Pherzawl'),
    ('14', N'Manipur', '257', N'Senapati'),
    ('14', N'Manipur', '258', N'Tamenglong'),
    ('14', N'Manipur', '716', N'Tengnoupal'),
    ('14', N'Manipur', '259', N'Thoubal'),
    ('14', N'Manipur', '260', N'Ukhrul'),
    ('17', N'Meghalaya', '740', N'Eastern West Khasi Hills'),
    ('17', N'Meghalaya', '273', N'East Garo Hills'),
    ('17', N'Meghalaya', '657', N'East Jaintia Hills'),
    ('17', N'Meghalaya', '274', N'East Khasi Hills'),
    ('17', N'Meghalaya', '656', N'North Garo Hills'),
    ('17', N'Meghalaya', '276', N'Ri Bhoi'),
    ('17', N'Meghalaya', '277', N'South Garo Hills'),
    ('17', N'Meghalaya', '663', N'South West Garo Hills'),
    ('17', N'Meghalaya', '658', N'South West Khasi Hills'),
    ('17', N'Meghalaya', '278', N'West Garo Hills'),
    ('17', N'Meghalaya', '275', N'West Jaintia Hills'),
    ('17', N'Meghalaya', '279', N'West Khasi Hills'),
    ('15', N'Mizoram', '261', N'Aizawl'),
    ('15', N'Mizoram', '262', N'Champhai'),
    ('15', N'Mizoram', '726', N'Hnahthial'),
    ('15', N'Mizoram', '728', N'Khawzawl'),
    ('15', N'Mizoram', '263', N'Kolasib'),
    ('15', N'Mizoram', '264', N'Lawngtlai'),
    ('15', N'Mizoram', '265', N'Lunglei'),
    ('15', N'Mizoram', '266', N'Mamit'),
    ('15', N'Mizoram', '727', N'Saitual'),
    ('15', N'Mizoram', '268', N'Serchhip'),
    ('15', N'Mizoram', '267', N'Siaha'),
    ('13', N'Nagaland', '758', N'Chumoukedima'),
    ('13', N'Nagaland', '244', N'Dimapur'),
    ('13', N'Nagaland', '614', N'Kiphire'),
    ('13', N'Nagaland', '245', N'Kohima'),
    ('13', N'Nagaland', '615', N'Longleng'),
    ('13', N'Nagaland', '788', N'Meluri'),
    ('13', N'Nagaland', '246', N'Mokokchung'),
    ('13', N'Nagaland', '247', N'Mon'),
    ('13', N'Nagaland', '764', N'Niuland'),
    ('13', N'Nagaland', '736', N'Noklak'),
    ('13', N'Nagaland', '613', N'Peren'),
    ('13', N'Nagaland', '248', N'Phek'),
    ('13', N'Nagaland', '765', N'Shamator'),
    ('13', N'Nagaland', '757', N'Tseminyu'),
    ('13', N'Nagaland', '249', N'Tuensang'),
    ('13', N'Nagaland', '250', N'Wokha'),
    ('13', N'Nagaland', '251', N'Zunheboto'),
    ('21', N'Odisha', '344', N'Anugola'),
    ('21', N'Odisha', '345', N'Balangir'),
    ('21', N'Odisha', '346', N'Baleshwar'),
    ('21', N'Odisha', '347', N'Baragada'),
    ('21', N'Odisha', '348', N'Bhadrak'),
    ('21', N'Odisha', '349', N'Boudh'),
    ('21', N'Odisha', '351', N'Debagada'),
    ('21', N'Odisha', '352', N'Dhenkanal'),
    ('21', N'Odisha', '353', N'Gajapati'),
    ('21', N'Odisha', '354', N'Ganjam'),
    ('21', N'Odisha', '355', N'Jagatsinghapur'),
    ('21', N'Odisha', '356', N'Jajpur'),
    ('21', N'Odisha', '357', N'Jharsuguda'),
    ('21', N'Odisha', '358', N'Kalahandi'),
    ('21', N'Odisha', '359', N'Kandhamala'),
    ('21', N'Odisha', '350', N'Kataka'),
    ('21', N'Odisha', '360', N'Kendrapada'),
    ('21', N'Odisha', '361', N'Kendujhar'),
    ('21', N'Odisha', '362', N'Khordha'),
    ('21', N'Odisha', '363', N'Koraput'),
    ('21', N'Odisha', '364', N'Malkangiri'),
    ('21', N'Odisha', '365', N'Mayurbhanj'),
    ('21', N'Odisha', '366', N'Nabarangpur'),
    ('21', N'Odisha', '367', N'Nayagada'),
    ('21', N'Odisha', '368', N'Nuapada'),
    ('21', N'Odisha', '369', N'Puri'),
    ('21', N'Odisha', '370', N'Rayagada'),
    ('21', N'Odisha', '371', N'Sambalpur'),
    ('21', N'Odisha', '372', N'Subarnapur'),
    ('21', N'Odisha', '373', N'Sundaragada'),
    ('34', N'Puducherry', '598', N'Karaikal'),
    ('34', N'Puducherry', '600', N'Puducherry'),
    ('3', N'Punjab', '27', N'Amritsar'),
    ('3', N'Punjab', '605', N'Barnala'),
    ('3', N'Punjab', '28', N'Bathinda'),
    ('3', N'Punjab', '29', N'Faridkot'),
    ('3', N'Punjab', '30', N'Fatehgarh Sahib'),
    ('3', N'Punjab', '651', N'Fazilka'),
    ('3', N'Punjab', '31', N'Ferozepur'),
    ('3', N'Punjab', '32', N'Gurdaspur'),
    ('3', N'Punjab', '33', N'Hoshiarpur'),
    ('3', N'Punjab', '34', N'Jalandhar'),
    ('3', N'Punjab', '35', N'Kapurthala'),
    ('3', N'Punjab', '36', N'Ludhiana'),
    ('3', N'Punjab', '737', N'Malerkotla'),
    ('3', N'Punjab', '37', N'Mansa'),
    ('3', N'Punjab', '38', N'Moga'),
    ('3', N'Punjab', '662', N'Pathankot'),
    ('3', N'Punjab', '41', N'Patiala'),
    ('3', N'Punjab', '42', N'Rupnagar'),
    ('3', N'Punjab', '43', N'Sangrur'),
    ('3', N'Punjab', '608', N'S.A.S Nagar'),
    ('3', N'Punjab', '40', N'Shahid Bhagat Singh Nagar'),
    ('3', N'Punjab', '39', N'Sri Muktsar Sahib'),
    ('3', N'Punjab', '609', N'Tarn Taran'),
    ('8', N'Rajasthan', '86', N'Ajmer'),
    ('8', N'Rajasthan', '87', N'Alwar'),
    ('8', N'Rajasthan', '775', N'Balotra'),
    ('8', N'Rajasthan', '88', N'Banswara'),
    ('8', N'Rajasthan', '89', N'Baran'),
    ('8', N'Rajasthan', '90', N'Barmer'),
    ('8', N'Rajasthan', '774', N'Beawar'),
    ('8', N'Rajasthan', '91', N'Bharatpur'),
    ('8', N'Rajasthan', '92', N'Bhilwara'),
    ('8', N'Rajasthan', '93', N'Bikaner'),
    ('8', N'Rajasthan', '94', N'Bundi'),
    ('8', N'Rajasthan', '95', N'Chittorgarh'),
    ('8', N'Rajasthan', '96', N'Churu'),
    ('8', N'Rajasthan', '97', N'Dausa'),
    ('8', N'Rajasthan', '767', N'Deeg'),
    ('8', N'Rajasthan', '98', N'Dholpur'),
    ('8', N'Rajasthan', '768', N'Didwana-Kuchaman'),
    ('8', N'Rajasthan', '99', N'Dungarpur'),
    ('8', N'Rajasthan', '100', N'Ganganagar'),
    ('8', N'Rajasthan', '101', N'Hanumangarh'),
    ('8', N'Rajasthan', '102', N'Jaipur'),
    ('8', N'Rajasthan', '103', N'Jaisalmer'),
    ('8', N'Rajasthan', '104', N'Jalore'),
    ('8', N'Rajasthan', '105', N'Jhalawar'),
    ('8', N'Rajasthan', '106', N'Jhunjhunu'),
    ('8', N'Rajasthan', '107', N'Jodhpur'),
    ('8', N'Rajasthan', '108', N'Karauli'),
    ('8', N'Rajasthan', '770', N'Khairthal-Tijara'),
    ('8', N'Rajasthan', '109', N'Kota'),
    ('8', N'Rajasthan', '782', N'Kotputli-Behror'),
    ('8', N'Rajasthan', '110', N'Nagaur'),
    ('8', N'Rajasthan', '111', N'Pali'),
    ('8', N'Rajasthan', '772', N'Phalodi'),
    ('8', N'Rajasthan', '629', N'Pratapgarh'),
    ('8', N'Rajasthan', '112', N'Rajsamand'),
    ('8', N'Rajasthan', '777', N'Salumbar'),
    ('8', N'Rajasthan', '113', N'Sawai Madhopur'),
    ('8', N'Rajasthan', '114', N'Sikar'),
    ('8', N'Rajasthan', '115', N'Sirohi'),
    ('8', N'Rajasthan', '116', N'Tonk'),
    ('8', N'Rajasthan', '117', N'Udaipur'),
    ('11', N'Sikkim', '225', N'Gangtok'),
    ('11', N'Sikkim', '228', N'Gyalshing'),
    ('11', N'Sikkim', '226', N'Mangan'),
    ('11', N'Sikkim', '227', N'Namchi'),
    ('11', N'Sikkim', '741', N'Pakyong'),
    ('11', N'Sikkim', '742', N'Soreng'),
    ('33', N'Tamil Nadu', '610', N'Ariyalur'),
    ('33', N'Tamil Nadu', '730', N'Chengalpattu'),
    ('33', N'Tamil Nadu', '568', N'Chennai'),
    ('33', N'Tamil Nadu', '569', N'Coimbatore'),
    ('33', N'Tamil Nadu', '570', N'Cuddalore'),
    ('33', N'Tamil Nadu', '571', N'Dharmapuri'),
    ('33', N'Tamil Nadu', '572', N'Dindigul'),
    ('33', N'Tamil Nadu', '573', N'Erode'),
    ('33', N'Tamil Nadu', '729', N'Kallakurichi'),
    ('33', N'Tamil Nadu', '574', N'Kancheepuram'),
    ('33', N'Tamil Nadu', '575', N'Kanniyakumari'),
    ('33', N'Tamil Nadu', '576', N'Karur'),
    ('33', N'Tamil Nadu', '577', N'Krishnagiri'),
    ('33', N'Tamil Nadu', '578', N'Madurai'),
    ('33', N'Tamil Nadu', '735', N'Mayiladuthurai'),
    ('33', N'Tamil Nadu', '579', N'Nagapattinam'),
    ('33', N'Tamil Nadu', '580', N'Namakkal'),
    ('33', N'Tamil Nadu', '581', N'Perambalur'),
    ('33', N'Tamil Nadu', '582', N'Pudukkottai'),
    ('33', N'Tamil Nadu', '583', N'Ramanathapuram'),
    ('33', N'Tamil Nadu', '731', N'Ranipet'),
    ('33', N'Tamil Nadu', '584', N'Salem'),
    ('33', N'Tamil Nadu', '585', N'Sivaganga'),
    ('33', N'Tamil Nadu', '733', N'Tenkasi'),
    ('33', N'Tamil Nadu', '586', N'Thanjavur'),
    ('33', N'Tamil Nadu', '588', N'Theni'),
    ('33', N'Tamil Nadu', '587', N'The Nilgiris'),
    ('33', N'Tamil Nadu', '589', N'Thiruvallur'),
    ('33', N'Tamil Nadu', '590', N'Thiruvarur'),
    ('33', N'Tamil Nadu', '594', N'Thoothukkudi'),
    ('33', N'Tamil Nadu', '591', N'Tiruchirappalli'),
    ('33', N'Tamil Nadu', '592', N'Tirunelveli'),
    ('33', N'Tamil Nadu', '732', N'Tirupathur'),
    ('33', N'Tamil Nadu', '634', N'Tiruppur'),
    ('33', N'Tamil Nadu', '593', N'Tiruvannamalai'),
    ('33', N'Tamil Nadu', '595', N'Vellore'),
    ('33', N'Tamil Nadu', '596', N'Viluppuram'),
    ('33', N'Tamil Nadu', '597', N'Virudhunagar'),
    ('36', N'Telangana', '501', N'Adilabad'),
    ('36', N'Telangana', '690', N'Bhadradri Kothagudem'),
    ('36', N'Telangana', '686', N'Hanumakonda'),
    ('36', N'Telangana', '507', N'Hyderabad'),
    ('36', N'Telangana', '681', N'Jagitial'),
    ('36', N'Telangana', '689', N'Jangoan'),
    ('36', N'Telangana', '687', N'Jayashankar Bhupalapally'),
    ('36', N'Telangana', '695', N'Jogulamba Gadwal'),
    ('36', N'Telangana', '685', N'Kamareddy'),
    ('36', N'Telangana', '508', N'Karimnagar'),
    ('36', N'Telangana', '509', N'Khammam'),
    ('36', N'Telangana', '699', N'Kumuram Bheem Asifabad'),
    ('36', N'Telangana', '688', N'Mahabubabad'),
    ('36', N'Telangana', '512', N'Mahabubnagar'),
    ('36', N'Telangana', '684', N'Mancherial'),
    ('36', N'Telangana', '513', N'Medak'),
    ('36', N'Telangana', '700', N'Medchal Malkajgiri'),
    ('36', N'Telangana', '720', N'Mulugu'),
    ('36', N'Telangana', '694', N'Nagarkurnool'),
    ('36', N'Telangana', '514', N'Nalgonda'),
    ('36', N'Telangana', '721', N'Narayanpet'),
    ('36', N'Telangana', '680', N'Nirmal'),
    ('36', N'Telangana', '516', N'Nizamabad'),
    ('36', N'Telangana', '682', N'Peddapalli'),
    ('36', N'Telangana', '683', N'Rajanna Sircilla'),
    ('36', N'Telangana', '518', N'Ranga Reddy'),
    ('36', N'Telangana', '691', N'Sangareddy'),
    ('36', N'Telangana', '692', N'Siddipet'),
    ('36', N'Telangana', '696', N'Suryapet'),
    ('36', N'Telangana', '698', N'Vikarabad'),
    ('36', N'Telangana', '693', N'Wanaparthy'),
    ('36', N'Telangana', '522', N'Warangal'),
    ('36', N'Telangana', '697', N'Yadadri Bhuvanagiri'),
    ('38', N'The Dadra And Nagar Haveli And Daman And Diu', '465', N'Dadra And Nagar Haveli'),
    ('38', N'The Dadra And Nagar Haveli And Daman And Diu', '463', N'Daman'),
    ('38', N'The Dadra And Nagar Haveli And Daman And Diu', '464', N'Diu'),
    ('16', N'Tripura', '269', N'Dhalai'),
    ('16', N'Tripura', '654', N'Gomati'),
    ('16', N'Tripura', '652', N'Khowai'),
    ('16', N'Tripura', '270', N'North Tripura'),
    ('16', N'Tripura', '653', N'Sepahijala'),
    ('16', N'Tripura', '271', N'South Tripura'),
    ('16', N'Tripura', '655', N'Unakoti'),
    ('16', N'Tripura', '272', N'West Tripura'),
    ('5', N'Uttarakhand', '45', N'Almora'),
    ('5', N'Uttarakhand', '46', N'Bageshwar'),
    ('5', N'Uttarakhand', '47', N'Chamoli'),
    ('5', N'Uttarakhand', '48', N'Champawat'),
    ('5', N'Uttarakhand', '49', N'Dehradun'),
    ('5', N'Uttarakhand', '50', N'Haridwar'),
    ('5', N'Uttarakhand', '51', N'Nainital'),
    ('5', N'Uttarakhand', '52', N'Pauri Garhwal'),
    ('5', N'Uttarakhand', '53', N'Pithoragarh'),
    ('5', N'Uttarakhand', '54', N'Rudraprayag'),
    ('5', N'Uttarakhand', '55', N'Tehri Garhwal'),
    ('5', N'Uttarakhand', '56', N'Udham Singh Nagar'),
    ('5', N'Uttarakhand', '57', N'Uttarkashi'),
    ('9', N'Uttar Pradesh', '118', N'Agra'),
    ('9', N'Uttar Pradesh', '119', N'Aligarh'),
    ('9', N'Uttar Pradesh', '121', N'Ambedkar Nagar'),
    ('9', N'Uttar Pradesh', '640', N'Amethi'),
    ('9', N'Uttar Pradesh', '154', N'Amroha'),
    ('9', N'Uttar Pradesh', '122', N'Auraiya'),
    ('9', N'Uttar Pradesh', '140', N'Ayodhya'),
    ('9', N'Uttar Pradesh', '123', N'Azamgarh'),
    ('9', N'Uttar Pradesh', '124', N'Baghpat'),
    ('9', N'Uttar Pradesh', '125', N'Bahraich'),
    ('9', N'Uttar Pradesh', '126', N'Ballia'),
    ('9', N'Uttar Pradesh', '127', N'Balrampur'),
    ('9', N'Uttar Pradesh', '128', N'Banda'),
    ('9', N'Uttar Pradesh', '129', N'Bara Banki'),
    ('9', N'Uttar Pradesh', '130', N'Bareilly'),
    ('9', N'Uttar Pradesh', '131', N'Basti'),
    ('9', N'Uttar Pradesh', '179', N'Bhadohi'),
    ('9', N'Uttar Pradesh', '132', N'Bijnor'),
    ('9', N'Uttar Pradesh', '133', N'Budaun'),
    ('9', N'Uttar Pradesh', '134', N'Bulandshahr'),
    ('9', N'Uttar Pradesh', '135', N'Chandauli'),
    ('9', N'Uttar Pradesh', '136', N'Chitrakoot'),
    ('9', N'Uttar Pradesh', '137', N'Deoria'),
    ('9', N'Uttar Pradesh', '138', N'Etah'),
    ('9', N'Uttar Pradesh', '139', N'Etawah'),
    ('9', N'Uttar Pradesh', '141', N'Farrukhabad'),
    ('9', N'Uttar Pradesh', '142', N'Fatehpur'),
    ('9', N'Uttar Pradesh', '143', N'Firozabad'),
    ('9', N'Uttar Pradesh', '144', N'Gautam Buddha Nagar'),
    ('9', N'Uttar Pradesh', '145', N'Ghaziabad'),
    ('9', N'Uttar Pradesh', '146', N'Ghazipur'),
    ('9', N'Uttar Pradesh', '147', N'Gonda'),
    ('9', N'Uttar Pradesh', '148', N'Gorakhpur'),
    ('9', N'Uttar Pradesh', '149', N'Hamirpur'),
    ('9', N'Uttar Pradesh', '661', N'Hapur'),
    ('9', N'Uttar Pradesh', '150', N'Hardoi'),
    ('9', N'Uttar Pradesh', '163', N'Hathras'),
    ('9', N'Uttar Pradesh', '151', N'Jalaun'),
    ('9', N'Uttar Pradesh', '152', N'Jaunpur'),
    ('9', N'Uttar Pradesh', '153', N'Jhansi'),
    ('9', N'Uttar Pradesh', '155', N'Kannauj'),
    ('9', N'Uttar Pradesh', '156', N'Kanpur Dehat'),
    ('9', N'Uttar Pradesh', '157', N'Kanpur Nagar'),
    ('9', N'Uttar Pradesh', '633', N'Kasganj'),
    ('9', N'Uttar Pradesh', '158', N'Kaushambi'),
    ('9', N'Uttar Pradesh', '159', N'Kheri'),
    ('9', N'Uttar Pradesh', '160', N'Kushinagar'),
    ('9', N'Uttar Pradesh', '161', N'Lalitpur'),
    ('9', N'Uttar Pradesh', '162', N'Lucknow'),
    ('9', N'Uttar Pradesh', '165', N'Mahoba'),
    ('9', N'Uttar Pradesh', '164', N'Mahrajganj'),
    ('9', N'Uttar Pradesh', '166', N'Mainpuri'),
    ('9', N'Uttar Pradesh', '167', N'Mathura'),
    ('9', N'Uttar Pradesh', '168', N'Mau'),
    ('9', N'Uttar Pradesh', '169', N'Meerut'),
    ('9', N'Uttar Pradesh', '170', N'Mirzapur'),
    ('9', N'Uttar Pradesh', '171', N'Moradabad'),
    ('9', N'Uttar Pradesh', '172', N'Muzaffarnagar'),
    ('9', N'Uttar Pradesh', '173', N'Pilibhit'),
    ('9', N'Uttar Pradesh', '174', N'Pratapgarh'),
    ('9', N'Uttar Pradesh', '120', N'Prayagraj'),
    ('9', N'Uttar Pradesh', '175', N'Rae Bareli'),
    ('9', N'Uttar Pradesh', '176', N'Rampur'),
    ('9', N'Uttar Pradesh', '177', N'Saharanpur'),
    ('9', N'Uttar Pradesh', '659', N'Sambhal'),
    ('9', N'Uttar Pradesh', '178', N'Sant Kabir Nagar'),
    ('9', N'Uttar Pradesh', '180', N'Shahjahanpur'),
    ('9', N'Uttar Pradesh', '660', N'Shamli'),
    ('9', N'Uttar Pradesh', '181', N'Shrawasti'),
    ('9', N'Uttar Pradesh', '182', N'Siddharthnagar'),
    ('9', N'Uttar Pradesh', '183', N'Sitapur'),
    ('9', N'Uttar Pradesh', '184', N'Sonbhadra'),
    ('9', N'Uttar Pradesh', '185', N'Sultanpur'),
    ('9', N'Uttar Pradesh', '186', N'Unnao'),
    ('9', N'Uttar Pradesh', '187', N'Varanasi'),
    ('19', N'West Bengal', '664', N'Alipurduar'),
    ('19', N'West Bengal', '305', N'Bankura'),
    ('19', N'West Bengal', '307', N'Birbhum'),
    ('19', N'West Bengal', '308', N'Cooch Behar'),
    ('19', N'West Bengal', '310', N'Dakshin Dinajpur'),
    ('19', N'West Bengal', '309', N'Darjeeling'),
    ('19', N'West Bengal', '312', N'Hooghly'),
    ('19', N'West Bengal', '313', N'Howrah'),
    ('19', N'West Bengal', '314', N'Jalpaiguri'),
    ('19', N'West Bengal', '703', N'Jhargram'),
    ('19', N'West Bengal', '702', N'Kalimpong'),
    ('19', N'West Bengal', '315', N'Kolkata'),
    ('19', N'West Bengal', '316', N'Malda'),
    ('19', N'West Bengal', '319', N'Murshidabad'),
    ('19', N'West Bengal', '320', N'Nadia'),
    ('19', N'West Bengal', '303', N'North 24 Parganas'),
    ('19', N'West Bengal', '704', N'Paschim Bardhaman'),
    ('19', N'West Bengal', '318', N'Paschim Medinipur'),
    ('19', N'West Bengal', '306', N'Purba Bardhaman'),
    ('19', N'West Bengal', '317', N'Purba Medinipur'),
    ('19', N'West Bengal', '321', N'Purulia'),
    ('19', N'West Bengal', '304', N'South 24 Parganas'),
    ('19', N'West Bengal', '311', N'Uttar Dinajpur');

-- A previous run of this script (before the name was normalised) may have
-- created a second row for the same state. Fold it back: move its districts to
-- the original, then remove it.
DECLARE @dupes TABLE (KeepId smallint, DropId smallint);

INSERT INTO @dupes (KeepId, DropId)
SELECT MIN(s.StateId), MAX(s.StateId)
FROM   master.State AS s
GROUP  BY dbo.fn_NormaliseStateName(s.Name)
HAVING COUNT(*) > 1;

UPDATE d
SET    d.StateId = x.KeepId
FROM   master.District AS d
INNER JOIN @dupes AS x ON x.DropId = d.StateId
WHERE  NOT EXISTS
(
    SELECT 1 FROM master.District AS k
    WHERE k.StateId = x.KeepId AND LOWER(k.Name) = LOWER(d.Name)
);

DELETE d
FROM   master.District AS d
INNER JOIN @dupes AS x ON x.DropId = d.StateId;

UPDATE s
SET    s.Code = COALESCE(dup.Code, s.Code)
FROM   master.State AS s
INNER JOIN @dupes AS x ON x.KeepId = s.StateId
INNER JOIN master.State AS dup ON dup.StateId = x.DropId;

DELETE s
FROM   master.State AS s
INNER JOIN @dupes AS x ON x.DropId = s.StateId;

-- ------------------------------------------------------------- states ---
-- Names differ in case and in "And"/"and", so the match is case-insensitive
-- and normalises the conjunction.
UPDATE s
SET    s.Code = x.StateCode
FROM   master.State AS s
INNER JOIN
(
    SELECT DISTINCT StateCode, StateName FROM #Src
) AS x
    ON dbo.fn_NormaliseStateName(s.Name) = dbo.fn_NormaliseStateName(x.StateName);

-- Anything in the file the portal does not yet know about.
INSERT INTO master.State (Code, Name, IsUnionTerritory, IsNorthEastern, IsActive)
SELECT DISTINCT x.StateCode, x.StateName, 0, 0, 1
FROM   (SELECT DISTINCT StateCode, StateName FROM #Src) AS x
WHERE  NOT EXISTS
(
    SELECT 1 FROM master.State AS s
    WHERE dbo.fn_NormaliseStateName(s.Name) = dbo.fn_NormaliseStateName(x.StateName)
       OR s.Code = x.StateCode
);

-- ---------------------------------------------------------- districts ---
-- master.District carries UQ_District on (StateId, Name), and the earlier seed
-- already holds districts under their own codes. So the official code is first
-- stamped onto the row that already bears that name, and only what remains is
-- inserted — otherwise every pre-existing district would collide on its name.
WITH Official AS
(
    SELECT s.StateId, x.DistrictCode, x.DistrictName
    FROM   #Src AS x
    INNER JOIN master.State AS s ON s.Code = x.StateCode
)
UPDATE d
SET    d.Code = o.DistrictCode,
       d.Name = o.DistrictName,
       d.IsActive = 1
FROM   master.District AS d
INNER JOIN Official AS o
    ON  o.StateId = d.StateId
    AND LOWER(o.DistrictName) = LOWER(d.Name);

-- Now the genuinely new ones.
INSERT INTO master.District (StateId, Code, Name, IsActive)
SELECT s.StateId, x.DistrictCode, x.DistrictName, 1
FROM   #Src AS x
INNER JOIN master.State AS s ON s.Code = x.StateCode
WHERE  NOT EXISTS
(
    SELECT 1 FROM master.District AS d
    WHERE d.StateId = s.StateId
      AND (d.Code = x.DistrictCode OR LOWER(d.Name) = LOWER(x.DistrictName))
);

-- Districts seeded earlier without an official code. They are deactivated
-- rather than deleted: enterprises may already reference them.
UPDATE master.District
SET    IsActive = 0
WHERE  Code IS NULL OR Code NOT IN (SELECT DistrictCode FROM #Src);

DROP TABLE #Src;

COMMIT TRANSACTION;

SELECT 'states'    AS Entity, COUNT(*) AS Rows FROM master.State
UNION ALL
SELECT 'districts', COUNT(*) FROM master.District WHERE IsActive = 1
UNION ALL
SELECT 'deactivated', COUNT(*) FROM master.District WHERE IsActive = 0;
